spring:
  profiles:
    active: smart
  thymeleaf:
    cache: false
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
  datasource:
    url: jdbc:postgresql://localhost:5432/WebuniSpringHr
    username: postgres
    password: supernova
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false

hr:
  employeesalary:
    def:
      percent: 5
    smart:
      limit: [10, 5, 2.5]
      percent: [10, 5, 2]

server:
  error:
    include-message: always
